# Generated by Django 5.2.14 on 2026-05-20 04:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_alter_order_options_alter_orderitem_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("AIRTEL", "Airtel Money"),
                            ("MOOV", "Moov Money"),
                            ("CARD", "Carte Bancaire (Stripe)"),
                            ("CASH", "Espèces (À la livraison/caisse)"),
                        ],
                        help_text="Méthode de paiement choisie par l'utilisateur.",
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total de la transaction.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En traitement"),
                            ("SUCCESS", "Payé / Succès"),
                            ("FAILED", "Échoué"),
                            ("CANCELLED", "Annulé"),
                            ("REFUNDED", "Remboursé"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID de transaction fourni par le prestataire (Stripe, Airtel, Moov).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, help_text="Date effective du paiement.", null=True
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        help_text="Données brutes de la réponse API (Airtel, Moov, Stripe).",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cash_verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pharmacien ayant confirmé la réception du cash.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_cash_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ("-created_at",),
            },
        ),
    ]
