# Generated by Django 5.2.14 on 2026-05-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_user", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("PATIENT", "Patient"),
                    ("PHARMACIST", "Pharmacien"),
                    ("ADMIN", "Administrateur"),
                ],
                default="PATIENT",
                max_length=20,
            ),
        ),
    ]
