# Generated by Django 5.2.14 on 2026-05-20 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "medications",
            "0002_alter_medication_id_alter_medicationcategory_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medication",
            options={"ordering": ["name"], "verbose_name_plural": "Médicaments"},
        ),
        migrations.AlterModelOptions(
            name="medicationcategory",
            options={"verbose_name_plural": "Catégories de médicaments"},
        ),
        migrations.AlterModelOptions(
            name="pharmacymedication",
            options={
                "verbose_name": "Stock Pharmacie",
                "verbose_name_plural": "Stocks Pharmacies",
            },
        ),
        migrations.AlterModelOptions(
            name="stockhistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Historique de stock",
            },
        ),
        migrations.AlterField(
            model_name="medication",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medications",
                to="medications.medicationcategory",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="medications/", verbose_name="Image"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="is_rare",
            field=models.BooleanField(default=False, verbose_name="Médicament rare"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="manufacturer",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Laboratoire"
            ),
        ),
        migrations.AlterField(
            model_name="medication",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nom du médicament"),
        ),
        migrations.AlterField(
            model_name="medication",
            name="requires_prescription",
            field=models.BooleanField(default=False, verbose_name="Ordonnance requise"),
        ),
        migrations.AlterField(
            model_name="pharmacymedication",
            name="is_available",
            field=models.BooleanField(default=True, verbose_name="Disponible"),
        ),
        migrations.AlterField(
            model_name="pharmacymedication",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Prix (FCFA)"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacymedication",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantité"),
        ),
        migrations.AlterField(
            model_name="pharmacymedication",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Dernière mise à jour"
            ),
        ),
        migrations.AlterField(
            model_name="stockhistory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date"),
        ),
        migrations.AlterField(
            model_name="stockhistory",
            name="new_quantity",
            field=models.IntegerField(verbose_name="Nouvelle quantité"),
        ),
        migrations.AlterField(
            model_name="stockhistory",
            name="previous_quantity",
            field=models.IntegerField(verbose_name="Quantité précédente"),
        ),
        migrations.AlterField(
            model_name="stockhistory",
            name="reason",
            field=models.CharField(blank=True, max_length=255, verbose_name="Raison"),
        ),
    ]
